- added automake 1.10 to available list in admin/cvs.sh
Changed files:
    koffice-build.patch -> 1.4

diff --git a/koffice-build.patch b/koffice-build.patch
--- a/koffice-build.patch
+++ b/koffice-build.patch
@@ -1,7 +1,7 @@
-diff -u -r koffice-1.4.95.orig/admin/acinclude.m4.in koffice-1.4.95/admin/acinclude.m4.in
---- koffice-1.4.95.orig/admin/acinclude.m4.in	2006-02-23 07:34:17.000000000 +0100
-+++ koffice-1.4.95/admin/acinclude.m4.in	2006-03-23 16:38:36.000000000 +0100
-@@ -4557,7 +4557,7 @@
+diff -ur org/admin/acinclude.m4.in mod/admin/acinclude.m4.in
+--- org/admin/acinclude.m4.in	2006-10-07 15:41:51.000000000 +0200
++++ mod/admin/acinclude.m4.in	2006-11-12 15:33:37.645747250 +0100
+@@ -4556,7 +4556,7 @@
  
  PYTHONINC=-I$python_incdir
  
@@ -10,9 +10,28 @@ diff -u -r koffice-1.4.95.orig/admin/acinclude.m4.in koffice-1.4.95/admin/acincl
  AC_FIND_FILE(libpython$version.so, $python_libdirs, python_libdir)
  if test ! -r $python_libdir/libpython$version.so; then
    AC_FIND_FILE(libpython$version.a, $python_libdirs, python_libdir)
-diff -u -r koffice-1.4.95.orig/kexi/kexidb/drivers/configure.in.in koffice-1.4.95/kexi/kexidb/drivers/configure.in.in
---- koffice-1.4.95.orig/kexi/kexidb/drivers/configure.in.in	2006-03-03 21:43:44.000000000 +0100
-+++ koffice-1.4.95/kexi/kexidb/drivers/configure.in.in	2006-03-23 16:44:44.000000000 +0100
+Tylko w mod/admin: acinclude.m4.in.orig
+diff -ur org/admin/cvs.sh mod/admin/cvs.sh
+--- org/admin/cvs.sh	2006-10-07 15:41:51.000000000 +0200
++++ mod/admin/cvs.sh	2006-11-12 15:39:17.787004750 +0100
+@@ -68,7 +68,7 @@
+     echo "*** KDE requires automake $required_automake_version"
+     exit 1
+     ;;
+-  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9*)
++  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9* | automake*1.10* )
+     echo "*** $AUTOMAKE_STRING found."
+     UNSERMAKE=no
+     ;;
+diff -ur org/filters/kpresenter/Makefile.am mod/filters/kpresenter/Makefile.am
+--- org/filters/kpresenter/Makefile.am	2006-10-07 15:33:06.000000000 +0200
++++ mod/filters/kpresenter/Makefile.am	2006-11-12 15:33:37.645747250 +0100
+@@ -1 +1 @@
+-SUBDIRS = libimageexport png bmp xbm xpm mng svg jpeg kword ooimpress
++SUBDIRS = libimageexport png bmp xbm xpm mng svg jpeg kword ooimpress powerpoint
+diff -ur org/kexi/kexidb/drivers/configure.in.in mod/kexi/kexidb/drivers/configure.in.in
+--- org/kexi/kexidb/drivers/configure.in.in	2006-10-07 15:28:55.000000000 +0200
++++ mod/kexi/kexidb/drivers/configure.in.in	2006-11-12 15:33:37.645747250 +0100
 @@ -54,8 +54,8 @@
  
      AC_MSG_CHECKING([for MySQL libraries])
@@ -24,8 +43,3 @@ diff -u -r koffice-1.4.95.orig/kexi/kexidb/drivers/configure.in.in koffice-1.4.9
        MYSQL_LIBS=$mysql_libdir
        AC_MSG_RESULT([$MYSQL_LIBS])
        AC_SUBST(MYSQL_LIBS)
---- koffice-1.5.92/filters/kpresenter/Makefile.am.orig	2006-09-20 08:51:36.000000000 +0200
-+++ koffice-1.5.92/filters/kpresenter/Makefile.am	2006-10-09 23:19:17.975582500 +0200
-@@ -1 +1 @@
--SUBDIRS = libimageexport png bmp xbm xpm mng svg jpeg kword ooimpress
-+SUBDIRS = libimageexport png bmp xbm xpm mng svg jpeg kword ooimpress powerpoint
